import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./providers/user";
import { BusyProvider } from "./providers/busy";
import { SymbolsProvider } from "./providers/symbols";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <BusyProvider>
      <UserProvider>
        <SymbolsProvider>
          <html lang="en">
            <body className={inter.className}>{children}</body>
          </html>
        </SymbolsProvider>
      </UserProvider>
    </BusyProvider>
  );
}
